# Installation script for Jira-Beads sync integration
# PowerShell version - equivalent to install.sh

$ErrorActionPreference = "Stop"

# Colors
function Write-ColorOutput {
    param(
        [string]$Message,
        [string]$Color = "White"
    )
    Write-Host $Message -ForegroundColor $Color
}

Write-ColorOutput "==========================================" "Cyan"
Write-ColorOutput "Jira-Beads Sync Installation" "Cyan"
Write-ColorOutput "==========================================" "Cyan"
Write-Host ""

# Check if we're in a git repository
try {
    $null = git rev-parse --git-dir 2>&1
} catch {
    Write-ColorOutput "❌ Not a git repository. Please run this from your project root." "Red"
    exit 1
}

$REPO_ROOT = git rev-parse --show-toplevel
$REPO_ROOT = $REPO_ROOT -replace '/', '\'
Write-ColorOutput "✓ Found git repository at: $REPO_ROOT" "Green"
Write-Host ""

# Check if bd is installed
$bdCommand = Get-Command bd -ErrorAction SilentlyContinue
if (-not $bdCommand) {
    Write-ColorOutput "❌ 'bd' command not found." "Red"
    Write-ColorOutput "Please install beads first:" "Yellow"
    Write-Host "  Windows: Download from https://github.com/steveyegge/beads/releases"
    Write-Host "  Or use WSL: curl -fsSL https://raw.githubusercontent.com/steveyegge/beads/main/scripts/install.sh | bash"
    exit 1
}
Write-ColorOutput "✓ Found bd command" "Green"
Write-Host ""

# Check if beads is initialized
$beadsDir = Join-Path $REPO_ROOT ".beads"
if (-not (Test-Path $beadsDir)) {
    Write-ColorOutput "⚠️  Beads not initialized in this repository." "Yellow"
    $response = Read-Host "Initialize beads now? (y/n)"
    if ($response -match '^[Yy]$') {
        Push-Location $REPO_ROOT
        bd init --quiet
        Pop-Location
        Write-ColorOutput "✓ Beads initialized" "Green"
        Write-Host ""
    } else {
        Write-ColorOutput "❌ Beads required. Exiting." "Red"
        exit 1
    }
} else {
    Write-ColorOutput "✓ Beads already initialized" "Green"
    Write-Host ""
}

# Create scripts directory if it doesn't exist
$scriptsDir = Join-Path $REPO_ROOT "scripts"
if (-not (Test-Path $scriptsDir)) {
    New-Item -ItemType Directory -Path $scriptsDir | Out-Null
}
Write-ColorOutput "✓ Created scripts directory" "Green"
Write-Host ""

# Copy sync script
$syncScript = "sync_jira_to_beads.py"
if (Test-Path $syncScript) {
    Copy-Item $syncScript -Destination (Join-Path $scriptsDir $syncScript) -Force
    Write-ColorOutput "✓ Copied sync script to scripts\sync_jira_to_beads.py" "Green"
    Write-Host ""
} else {
    Write-ColorOutput "❌ sync_jira_to_beads.py not found in current directory" "Red"
    exit 1
}

# Copy helper scripts for workflow automation
Write-ColorOutput "Installing workflow helpers..." "Cyan"

if (Test-Path "bd-start-branch.ps1") {
    Copy-Item "bd-start-branch.ps1" -Destination (Join-Path $scriptsDir "bd-start-branch.ps1") -Force
    Write-ColorOutput "✓ Installed bd-start-branch.ps1" "Green"
}

if (Test-Path "bd-finish.ps1") {
    Copy-Item "bd-finish.ps1" -Destination (Join-Path $scriptsDir "bd-finish.ps1") -Force
    Write-ColorOutput "✓ Installed bd-finish.ps1" "Green"
}

Write-Host ""

# Install git hook
$GIT_HOOKS_DIR = Join-Path $REPO_ROOT ".git\hooks"
if (-not (Test-Path $GIT_HOOKS_DIR)) {
    New-Item -ItemType Directory -Path $GIT_HOOKS_DIR -Force | Out-Null
}

Write-ColorOutput "Configure git hook?" "Yellow"
Write-Host "This will run the Jira sync automatically after 'git pull'"
$hookResponse = Read-Host "Install post-merge hook? (y/n)"
if ($hookResponse -match '^[Yy]$') {
    # Prompt for Jira configuration
    Write-Host ""
    $JIRA_PROJECT = Read-Host "Enter Jira project key (e.g., PROJ)"
    $JIRA_COMPONENT = Read-Host "Enter Jira component name (leave empty for all)"
    
    # Create customized hook (bash version for Git Bash on Windows)
    $hookContent = @"
#!/bin/bash
# Git post-merge hook for syncing Jira to beads
# Auto-generated by install.ps1

set -e

JIRA_PROJECT_KEY="$JIRA_PROJECT"
JIRA_COMPONENT="$JIRA_COMPONENT"
SYNC_SCRIPT="scripts/sync_jira_to_beads.py"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "`${BLUE}Running Jira-Beads sync...`${NC}"

REPO_ROOT=`$(git rev-parse --show-toplevel)

# Check if sync script exists
if [ ! -f "`$REPO_ROOT/`$SYNC_SCRIPT" ]; then
    echo -e "`${YELLOW}⚠️  Sync script not found. Skipping.`${NC}"
    exit 0
fi

# Only sync on main/master branch
CURRENT_BRANCH=`$(git rev-parse --abbrev-ref HEAD)
if [[ "`$CURRENT_BRANCH" != "main" && "`$CURRENT_BRANCH" != "master" ]]; then
    echo -e "`${YELLOW}ℹ️  Not on main/master branch. Skipping sync.`${NC}"
    exit 0
fi

cd "`$REPO_ROOT"

if [ -n "`$JIRA_COMPONENT" ]; then
    python3 "`$SYNC_SCRIPT" "`$JIRA_PROJECT_KEY" --component "`$JIRA_COMPONENT"
else
    python3 "`$SYNC_SCRIPT" "`$JIRA_PROJECT_KEY"
fi

exit 0
"@
    
    $hookPath = Join-Path $GIT_HOOKS_DIR "post-merge"
    Set-Content -Path $hookPath -Value $hookContent -NoNewline
    
    # On Windows with Git Bash, the hook should work as-is
    # If using PowerShell git hooks, create a .ps1 version
    $psHookContent = @"
# Git post-merge hook for syncing Jira to beads (PowerShell version)
# Auto-generated by install.ps1

`$ErrorActionPreference = "Stop"

`$JIRA_PROJECT_KEY = "$JIRA_PROJECT"
`$JIRA_COMPONENT = "$JIRA_COMPONENT"
`$SYNC_SCRIPT = "scripts\sync_jira_to_beads.py"

Write-Host "Running Jira-Beads sync..." -ForegroundColor Cyan

`$REPO_ROOT = git rev-parse --show-toplevel
`$REPO_ROOT = `$REPO_ROOT -replace '/', '\'

# Check if sync script exists
`$scriptPath = Join-Path `$REPO_ROOT `$SYNC_SCRIPT
if (-not (Test-Path `$scriptPath)) {
    Write-Host "⚠️  Sync script not found. Skipping." -ForegroundColor Yellow
    exit 0
}

# Only sync on main/master branch
`$CURRENT_BRANCH = git rev-parse --abbrev-ref HEAD
if (`$CURRENT_BRANCH -ne "main" -and `$CURRENT_BRANCH -ne "master") {
    Write-Host "ℹ️  Not on main/master branch. Skipping sync." -ForegroundColor Yellow
    exit 0
}

Push-Location `$REPO_ROOT

try {
    if (`$JIRA_COMPONENT) {
        python `$SYNC_SCRIPT `$JIRA_PROJECT_KEY --component `$JIRA_COMPONENT
    } else {
        python `$SYNC_SCRIPT `$JIRA_PROJECT_KEY
    }
} finally {
    Pop-Location
}

exit 0
"@
    
    $psHookPath = Join-Path $GIT_HOOKS_DIR "post-merge.ps1"
    Set-Content -Path $psHookPath -Value $psHookContent
    
    Write-ColorOutput "✓ Installed post-merge hook (both bash and PowerShell versions)" "Green"
    Write-Host ""
} else {
    Write-ColorOutput "Skipped hook installation" "Yellow"
    Write-Host ""
}

# Create config file for manual syncs
$configContent = @"
# Jira-Beads Sync Configuration
# Edit these values for your project

JIRA_PROJECT_KEY=$($JIRA_PROJECT ?? "PROJ")
JIRA_COMPONENT=$($JIRA_COMPONENT ?? "")
MCP_URL=https://mcp.atlassian.com/v1/mcp
"@

$configPath = Join-Path $REPO_ROOT ".jira-beads-config"
Set-Content -Path $configPath -Value $configContent
Write-ColorOutput "✓ Created .jira-beads-config" "Green"
Write-Host ""

# Add to .gitignore
$gitignorePath = Join-Path $REPO_ROOT ".gitignore"
if (Test-Path $gitignorePath) {
    $gitignoreContent = Get-Content $gitignorePath -Raw
    if ($gitignoreContent -notmatch ".jira-beads-config") {
        Add-Content -Path $gitignorePath -Value "`n.jira-beads-config"
        Write-ColorOutput "✓ Added .jira-beads-config to .gitignore" "Green"
        Write-Host ""
    }
}

Write-ColorOutput "==========================================" "Green"
Write-ColorOutput "✅ Installation Complete!" "Green"
Write-ColorOutput "==========================================" "Green"
Write-Host ""

Write-Host "Next steps:"
Write-Host "1. Test the sync manually:"
Write-Host "   cd $REPO_ROOT"
if ($JIRA_COMPONENT) {
    Write-Host "   python scripts\sync_jira_to_beads.py $JIRA_PROJECT --component $JIRA_COMPONENT"
} else {
    Write-Host "   python scripts\sync_jira_to_beads.py $($JIRA_PROJECT ?? 'PROJ')"
}
Write-Host ""
Write-Host "2. The sync will run automatically on 'git pull' (main/master branch only)"
Write-Host ""
Write-Host "3. Configure Atlassian MCP if not already done:"
Write-Host "   npx -y mcp-remote@0.1.13 https://mcp.atlassian.com/v1/mcp"
Write-Host ""
Write-Host "4. Use workflow helpers for easier development:"
Write-Host "   npm run start -- bd-a1b2   # Start issue + create branch"
Write-Host "   npm run finish -- bd-a1b2  # Finish issue + create PR"
Write-Host ""
Write-Host "   Or: node run start bd-a1b2 / node run finish bd-a1b2"
Write-Host ""
