#!/bin/bash
# Installation script for Jira-Beads sync integration

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}=========================================="
echo "Jira-Beads Sync Installation"
echo -e "==========================================${NC}\n"

# Check if we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo -e "${RED}❌ Not a git repository. Please run this from your project root.${NC}"
    exit 1
fi

REPO_ROOT=$(git rev-parse --show-toplevel)
echo -e "${GREEN}✓${NC} Found git repository at: $REPO_ROOT\n"

# Check if bd is installed
if ! command -v bd &> /dev/null; then
    echo -e "${RED}❌ 'bd' command not found.${NC}"
    echo -e "${YELLOW}Please install beads first:${NC}"
    echo "  curl -fsSL https://raw.githubusercontent.com/steveyegge/beads/main/scripts/install.sh | bash"
    exit 1
fi
echo -e "${GREEN}✓${NC} Found bd command\n"

# Check if beads is initialized
if [ ! -d "$REPO_ROOT/.beads" ]; then
    echo -e "${YELLOW}⚠️  Beads not initialized in this repository.${NC}"
    read -p "Initialize beads now? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        cd "$REPO_ROOT"
        bd init --quiet
        echo -e "${GREEN}✓${NC} Beads initialized\n"
    else
        echo -e "${RED}❌ Beads required. Exiting.${NC}"
        exit 1
    fi
else
    echo -e "${GREEN}✓${NC} Beads already initialized\n"
fi

# Create scripts directory if it doesn't exist
mkdir -p "$REPO_ROOT/scripts"
echo -e "${GREEN}✓${NC} Created scripts directory\n"

# Copy sync script
if [ -f "sync_jira_to_beads.py" ]; then
    cp sync_jira_to_beads.py "$REPO_ROOT/scripts/"
    chmod +x "$REPO_ROOT/scripts/sync_jira_to_beads.py"
    echo -e "${GREEN}✓${NC} Copied sync script to scripts/sync_jira_to_beads.py\n"
else
    echo -e "${RED}❌ sync_jira_to_beads.py not found in current directory${NC}"
    exit 1
fi

# Install git hook
GIT_HOOKS_DIR="$REPO_ROOT/.git/hooks"
if [ ! -d "$GIT_HOOKS_DIR" ]; then
    mkdir -p "$GIT_HOOKS_DIR"
fi

echo -e "${YELLOW}Configure git hook?${NC}"
echo "This will run the Jira sync automatically after 'git pull'"
read -p "Install post-merge hook? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    # Prompt for Jira configuration
    echo
    read -p "Enter Jira project key (e.g., PROJ): " JIRA_PROJECT
    read -p "Enter Jira component name (leave empty for all): " JIRA_COMPONENT
    
    # Create customized hook
    cat > "$GIT_HOOKS_DIR/post-merge" << EOF
#!/bin/bash
# Git post-merge hook for syncing Jira to beads
# Auto-generated by install.sh

set -e

JIRA_PROJECT_KEY="$JIRA_PROJECT"
JIRA_COMPONENT="$JIRA_COMPONENT"
SYNC_SCRIPT="scripts/sync_jira_to_beads.py"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "\${BLUE}Running Jira-Beads sync...\${NC}"

REPO_ROOT=\$(git rev-parse --show-toplevel)

# Check if sync script exists
if [ ! -f "\$REPO_ROOT/\$SYNC_SCRIPT" ]; then
    echo -e "\${YELLOW}⚠️  Sync script not found. Skipping.${NC}"
    exit 0
fi

# Only sync on main/master branch
CURRENT_BRANCH=\$(git rev-parse --abbrev-ref HEAD)
if [[ "\$CURRENT_BRANCH" != "main" && "\$CURRENT_BRANCH" != "master" ]]; then
    echo -e "\${YELLOW}ℹ️  Not on main/master branch. Skipping sync.${NC}"
    exit 0
fi

cd "\$REPO_ROOT"

if [ -n "\$JIRA_COMPONENT" ]; then
    python3 "\$SYNC_SCRIPT" "\$JIRA_PROJECT_KEY" --component "\$JIRA_COMPONENT"
else
    python3 "\$SYNC_SCRIPT" "\$JIRA_PROJECT_KEY"
fi

exit 0
EOF
    
    chmod +x "$GIT_HOOKS_DIR/post-merge"
    echo -e "${GREEN}✓${NC} Installed post-merge hook\n"
else
    echo -e "${YELLOW}Skipped hook installation${NC}\n"
fi

# Create config file for manual syncs
cat > "$REPO_ROOT/.jira-beads-config" << EOF
# Jira-Beads Sync Configuration
# Edit these values for your project

JIRA_PROJECT_KEY="${JIRA_PROJECT:-PROJ}"
JIRA_COMPONENT="${JIRA_COMPONENT:-}"
MCP_URL="https://mcp.atlassian.com/v1/mcp"
EOF

echo -e "${GREEN}✓${NC} Created .jira-beads-config\n"

# Add to .gitignore
if [ -f "$REPO_ROOT/.gitignore" ]; then
    if ! grep -q ".jira-beads-config" "$REPO_ROOT/.gitignore"; then
        echo ".jira-beads-config" >> "$REPO_ROOT/.gitignore"
        echo -e "${GREEN}✓${NC} Added .jira-beads-config to .gitignore\n"
    fi
fi

echo -e "${GREEN}=========================================="
echo "✅ Installation Complete!"
echo -e "==========================================${NC}\n"

echo "Next steps:"
echo "1. Test the sync manually:"
echo "   cd $REPO_ROOT"
echo "   python3 scripts/sync_jira_to_beads.py ${JIRA_PROJECT:-PROJ} ${JIRA_COMPONENT:+--component $JIRA_COMPONENT}"
echo
echo "2. The sync will run automatically on 'git pull' (main/master branch only)"
echo
echo "3. Configure Atlassian MCP if not already done:"
echo "   npx -y mcp-remote@0.1.13 https://mcp.atlassian.com/v1/mcp"
echo
