/**
 * HiveForge Issue Tracker Generator
 * Sets up issue tracker configurations and sync scripts
 */

const fs = require('fs');
const path = require('path');
const { copyTemplate, loadTemplate, getTemplatesDir } = require('../utils/templates');

/**
 * Issue tracker adapter configurations
 */
const adapters = {
  'github-issues': {
    name: 'GitHub Issues',
    secrets: [], // Uses GITHUB_TOKEN automatically
    files: ['github-issues'],
    syncCommand: 'gh issue list'
  },
  jira: {
    name: 'Jira',
    secrets: ['JIRA_HOST', 'JIRA_EMAIL', 'JIRA_API_TOKEN', 'JIRA_PROJECT_KEY'],
    files: ['jira'],
    syncCommand: 'npx hiveforge sync'
  },
  'gitlab-issues': {
    name: 'GitLab Issues',
    secrets: ['GITLAB_TOKEN', 'GITLAB_PROJECT_ID'],
    files: ['gitlab-issues'],
    syncCommand: 'npx hiveforge sync'
  },
  linear: {
    name: 'Linear',
    secrets: ['LINEAR_API_KEY', 'LINEAR_TEAM_ID'],
    files: ['linear'],
    syncCommand: 'npx hiveforge sync'
  }
};

/**
 * Generate issue tracker configuration
 * @param {object} config - HiveForge configuration
 * @returns {string[]} List of generated files
 */
async function generate(config) {
  const { issueTracker, projectPath } = config;

  if (!issueTracker || issueTracker === 'none') {
    return [];
  }

  const adapter = adapters[issueTracker];
  if (!adapter) {
    throw new Error(`Unknown issue tracker: ${issueTracker}`);
  }

  const files = [];
  const templatesDir = path.join(getTemplatesDir(), 'issue-trackers', issueTracker);

  // Create .beads directory if using beads
  if (config.agentTools && config.agentTools.includes('beads')) {
    const beadsDir = path.join(projectPath, '.beads');
    if (!fs.existsSync(beadsDir)) {
      fs.mkdirSync(beadsDir, { recursive: true });
    }

    // Create beads config.yaml
    const beadsConfigPath = path.join(beadsDir, 'config.yaml');
    if (!fs.existsSync(beadsConfigPath)) {
      const beadsConfig = generateBeadsConfig(issueTracker, config);
      fs.writeFileSync(beadsConfigPath, beadsConfig);
      files.push('.beads/config.yaml');
    }
  }

  // Copy issue tracker specific templates if they exist
  if (fs.existsSync(templatesDir)) {
    const entries = fs.readdirSync(templatesDir);
    for (const entry of entries) {
      const srcPath = path.join(templatesDir, entry);
      const destPath = path.join(projectPath, entry);

      if (fs.statSync(srcPath).isFile() && !fs.existsSync(destPath)) {
        const content = loadTemplate(srcPath, {
          ISSUE_TRACKER: adapter.name,
          SYNC_COMMAND: adapter.syncCommand
        });
        fs.writeFileSync(destPath, content);
        files.push(entry);
      }
    }
  }

  return files;
}

/**
 * Generate beads config.yaml content
 * @param {string} tracker - Issue tracker type
 * @param {object} config - HiveForge configuration
 * @returns {string} Config YAML content
 */
function generateBeadsConfig(tracker, config) {
  const configs = {
    jira: `# Beads Configuration
# Generated by HiveForge

source:
  type: jira
  host: \${JIRA_HOST}
  email: \${JIRA_EMAIL}
  project_key: \${JIRA_PROJECT_KEY}

sync:
  schedule: "${config.syncSchedule || '0 */6 * * *'}"
  auto_pr: ${config.autoCreatePR !== false}

filters:
  status:
    - "To Do"
    - "In Progress"
    - "Ready for Dev"
  exclude_labels:
    - "wontfix"
    - "duplicate"
`,
    'github-issues': `# Beads Configuration
# Generated by HiveForge

source:
  type: github-issues
  repo: \${GITHUB_REPOSITORY}

sync:
  schedule: "${config.syncSchedule || '0 */6 * * *'}"
  auto_pr: ${config.autoCreatePR !== false}

filters:
  state: open
  exclude_labels:
    - "wontfix"
    - "duplicate"
`,
    'gitlab-issues': `# Beads Configuration
# Generated by HiveForge

source:
  type: gitlab-issues
  project_id: \${GITLAB_PROJECT_ID}

sync:
  schedule: "${config.syncSchedule || '0 */6 * * *'}"
  auto_pr: ${config.autoCreatePR !== false}

filters:
  state: opened
  exclude_labels:
    - "wontfix"
    - "duplicate"
`,
    linear: `# Beads Configuration
# Generated by HiveForge

source:
  type: linear
  team_id: \${LINEAR_TEAM_ID}

sync:
  schedule: "${config.syncSchedule || '0 */6 * * *'}"
  auto_pr: ${config.autoCreatePR !== false}

filters:
  state:
    - "backlog"
    - "todo"
    - "in_progress"
`
  };

  return configs[tracker] || configs['github-issues'];
}

/**
 * Get adapter configuration
 * @param {string} tracker - Issue tracker type
 * @returns {object} Adapter configuration
 */
function getAdapter(tracker) {
  return adapters[tracker] || null;
}

/**
 * Get list of all available adapters
 * @returns {object} All adapters
 */
function getAdapters() {
  return adapters;
}

module.exports = {
  generate,
  getAdapter,
  getAdapters,
  adapters
};
